### ISSUE TITLE
Feature Request - How to custom sort sidebar?

### ISSUE THREAD

**Issue by imiskolee** [bukalapak/snowboard#92] opened 2019-11-25 02:26 UTC
Hi,Team:
  i have written a lots docs on snowbard, but i don't know how to control the left sidebar.

**Comment by MSchmidt** [comment] 2019-11-26 17:13
Might be duplicate of https://github.com/bukalapak/snowboard/issues/87

**Closed** 2019-11-29 06:08 UTC
